### ISSUE TITLE
Eclipse menu install software plugin site not working

### ISSUE THREAD

**Issue by adiaholic** [openframeworks/eclipsePlugin#5]
403 Forbidden
nginx/1.6.2

**Comment by rgkeith3** [comment]
Hey, sorry I may be doing it wrong, but I don't know where to look for help. installing it by adding the site gives me:
`Unable to read repository at http://openframeworks.cc/plugins/eclipse/content.xml.
Unable to read repository at http://openframeworks.cc/plugins/eclipse/content.xml.
sun.security.validator.ValidatorException: PKIX path building failed: sun.security.provider.certpath.SunCertPathBuilderException: unable to find valid certification path to requested target`

and as said above, when I navigate by regular browser I get the same 403. am I doing it wrong or is this a real issue?

**Comment by arturoc** [comment]
Hi sorry, this plugin is now deprecated and we don't host the site anymore i'm going to add a note but leave the repo open in case someone wants to fork it and maintain it themselves
